---
title: "R Programming Assignments"
author: "Paul Tunceren"
date: "2026-09-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Module 2 - Error Code
#assignment2 <- c(16, 18, 14, 22, 27, 17, 19, 17, 17, 22, 20, 22)
#myMean <- function(assignment2) {
#  return(sum(assignment) / length(someData))
#}
#myMean(assignment2)

```


```{r}
# Module 2 - Fixed Code
assignment2 <- c(16, 18, 14, 22, 27, 17, 19, 17, 17, 22, 20, 22)
myMean <- function(assignment2) {
  return(sum(assignment2) / length(assignment2))
}
myMean(assignment2)

```


```{r}
# Module 3
library(ggplot2)

# Values
Name <- c("Jeb", "Donald", "Ted", "Marco", "Carly", "Hillary", "Bernie")
ABC_poll   <- c(  4,      62,      51,    21,      2,        14,       15)
CBS_poll   <- c( 12,      75,      43,    19,      1,        21,       19)

# Combine into Dataframe
df_polls <- data.frame(Name, ABC_poll, CBS_poll)

# Inspecting Data
str(df_polls)
head(df_polls)

# Mean/Median/Range of polls
# Mean
mean(df_polls$ABC_poll)
mean(df_polls$CBS_poll)

# Median
median(df_polls$CBS_poll)
median(df_polls$ABC_poll)

# Range
range(df_polls[, c("ABC_poll","CBS_poll")])

# Difference between CBS and ABC polls
df_polls$Diff <- df_polls$CBS_poll - df_polls$ABC_poll
print(df_polls)

# bar chart
ggplot(df_polls, aes(x = Name,y = Diff)) +
geom_col()

```


```{r}
# Module 4
Frequency     <- c(0.6, 0.3, 0.4, 0.4, 0.2, 0.6, 0.3, 0.4, 0.9, 0.2)
BloodPressure <- c(103, 87, 32, 42, 59, 109, 78, 205, 135, 176)
FirstAssess   <- c(1, 1, 1, 1, 0, 0, 0, 0, NA, 1)    # bad=1, good=0
SecondAssess  <- c(0, 0, 1, 1, 0, 0, 1, 1, 1, 1)    # low=0, high=1
FinalDecision <- c(0, 1, 0, 1, 0, 1, 0, 1, 1, 1)    # low=0, high=1

df_hosp <- data.frame(
  Frequency, BloodPressure, FirstAssess,
  SecondAssess, FinalDecision, stringsAsFactors = FALSE
)
# Inspect and handle NA:
summary(df_hosp)
df_hosp <- na.omit(df_hosp)

boxplot(
  BloodPressure ~ FirstAssess,
  data = df_hosp,
  names = c("Good","Bad"),
  ylab = "Blood Pressure",
  main = "BP by First MD Assessment"
)

boxplot(
  BloodPressure ~ SecondAssess,
  data = df_hosp,
  names = c("Low","High"),
  ylab = "Blood Pressure",
  main = "BP by Second MD Assessment"
)

boxplot(
  BloodPressure ~ FinalDecision,
  data = df_hosp,
  names = c("Low","High"),
  ylab = "Blood Pressure",
  main = "BP by Final Decision"
)  
  
hist(
 df_hosp$Frequency,
 breaks = seq(0, 1, by = 0.1),
 xlab = "Visit Frequency",
 main = "Histogram of Visit Frequency"
)
  
hist(
 df_hosp$BloodPressure,
 breaks = 8,
 xlab = "Blood Pressure",
 main = "Histogram of Blood Pressure"
)
  
```


```{r}
# Module 5
A <- matrix(1:100,  nrow = 10)
B <- matrix(1:1000, nrow = 10)

dim(A)  # should be 10 × 10
dim(B)  # 10 × 100 — not square

# For A
invA <- solve(A)
detA <- det(A)

# For B, use tryCatch to capture errors
invB <- tryCatch(solve(B), error = function(e) e)
detB <- tryCatch(det(B),   error = function(e) e)

```

